AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
